clean: true

theme: fullwidth

output: docs
readme: README.md

module: Sysctl
swift_build_tool: spm
undocumented_text: ""
github_url: https://github.com/sersoft-gmbh/swift-sysctl

author: ser.soft GmbH
author_url: https://sersoft.de
